import type { Inquiry } from "@/lib/types";

export const inquiries: Inquiry[] = [
  {
    id: "inq-01",
    propertyId: "p-01",
    buyerId: "u-buyer-1",
    assignedSalesId: "u-sales-1",
    status: "SITE_VISIT",
    notes: "Family visit scheduled Saturday 11:00. Interested in the garden wing.",
    createdAt: "2026-07-02T09:12:00.000Z",
  },
  {
    id: "inq-02",
    propertyId: "p-02",
    buyerId: "u-buyer-2",
    assignedSalesId: "u-sales-1",
    status: "NEGOTIATION",
    notes: "Offered PKR 12.1 Cr. Waiting on seller counter.",
    createdAt: "2026-07-08T14:40:00.000Z",
  },
  {
    id: "inq-03",
    propertyId: "p-04",
    buyerId: "u-buyer-1",
    assignedSalesId: "u-sales-2",
    status: "CONTACTED",
    notes: "Called twice. Prefers weekday evening viewing.",
    createdAt: "2026-07-14T11:05:00.000Z",
  },
  {
    id: "inq-04",
    propertyId: "p-06",
    buyerId: "u-buyer-2",
    status: "NEW",
    notes: "Inbound from the listing page. First-time buyer.",
    createdAt: "2026-08-01T16:22:00.000Z",
  },
  {
    id: "inq-05",
    propertyId: "p-08",
    buyerId: "u-buyer-1",
    assignedSalesId: "u-sales-2",
    status: "ASSIGNED",
    notes: "Assigned to Hina. Needs school-run proximity notes.",
    createdAt: "2026-08-04T10:18:00.000Z",
  },
  {
    id: "inq-06",
    propertyId: "p-13",
    buyerId: "u-buyer-2",
    assignedSalesId: "u-sales-1",
    status: "CLOSED_WON",
    notes: "Token received. File with legal.",
    createdAt: "2026-05-19T08:00:00.000Z",
  },
  {
    id: "inq-07",
    propertyId: "p-03",
    buyerId: "u-buyer-1",
    assignedSalesId: "u-sales-1",
    status: "CLOSED_LOST",
    notes: "Buyer proceeded with a Margalla Road plot instead.",
    createdAt: "2026-04-11T13:30:00.000Z",
  },
  {
    id: "inq-08",
    propertyId: "p-09",
    buyerId: "u-buyer-2",
    assignedSalesId: "u-sales-2",
    status: "CONTACTED",
    notes: "WhatsApp thread open. Sending society bylaws.",
    createdAt: "2026-08-10T09:44:00.000Z",
  },
  {
    id: "inq-09",
    propertyId: "p-05",
    buyerId: "u-buyer-1",
    assignedSalesId: "u-sales-1",
    status: "NEW",
    notes: "High-intent inquiry from the map pin.",
    createdAt: "2026-08-16T07:55:00.000Z",
  },
  {
    id: "inq-10",
    propertyId: "p-15",
    buyerId: "u-buyer-2",
    assignedSalesId: "u-sales-2",
    status: "SITE_VISIT",
    notes: "Second visit with parents this Friday.",
    createdAt: "2026-07-22T15:10:00.000Z",
  },
];
